# -*- coding: utf-8 -*-
"""RetoPhyton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8B67XBaCILAdp7yBw01n1n49ePAWm-6
"""

import pandas as pd

# Especifica la ruta del archivo Excel
archivo_excel = 'bdlist.xlsx'

# Lee el archivo Excel y carga su contenido en un DataFrame de pandas
datos = pd.read_excel(archivo_excel)

# Muestra los primeros 5 registros del DataFrame para verificar que se haya cargado correctamente
print(datos.head())

pip install pandas

import pandas as pd
import matplotlib.pyplot as plt

# Leer el archivo Excel con los datos
archivo_excel = 'bdlist.xlsx'
datos_ventas = pd.read_excel(archivo_excel)

# Mostrar las primeras filas del DataFrame
print("Primeras filas de datos:")
print(datos_ventas.head())

# Obtener estadísticas descriptivas básicas
print("\nEstadísticas descriptivas:")
print(datos_ventas.describe())

ventas_por_producto = datos_ventas.groupby('ID')['Grupo de clientes'].sum().reset_index()

print("\nTotal de ventas por producto:")
print(ventas_por_producto)

# Crear un gráfico de barras para visualizar las ventas por producto
plt.figure(figsize=(10, 6))
plt.bar(ventas_por_producto['ID'], ventas_por_producto['Grupo de clientes'])
plt.title('Ventas por producto')
plt.xlabel('ID')
plt.ylabel('Grupo de clientes')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

ventas_por_region = datos_ventas.groupby('Grupo de clientes').agg({'ID': 'sum', 'ID': 'sum'}).reset_index()
print("\nTotal de ventas e ingresos por región:")
print(ventas_por_region)

# Visualizar las regiones con más ventas
plt.figure(figsize=(10, 6))
plt.bar(ventas_por_region['Grupo de clientes'], ventas_por_region['ID'])
plt.title('Nombre completo')
plt.xlabel('Grupo de clientes')
plt.ylabel('ID')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd

from google.colab import drive
drive.mount('BdDesafio.csv')

ruta_csv = '/content/BdDesafio.csv/MyDrive/FOTO PASAPORTE/BdDesafio.csv'

# Lee el archivo CSV y carga su contenido en un DataFrame de pandas
datos = pd.read_csv(ruta_csv)

# Muestra las primeras filas del DataFrame
print(datos.head())

nombres_columnas = datos.columns.tolist()
print("Nombres de las columnas:", nombres_columnas)

# Obtén los datos de una fila específica (por ejemplo, la primera fila)
fila_especifica = 0  # Cambia a la fila que desees
datos_fila = datos.iloc[fila_especifica]
print("Datos de la fila", fila_especifica, ":", datos_fila)

print("\nResumen estadístico:")
print(datos.describe())

ventas_por_categoria = datos.groupby('Category Name')['Sale (Dollars)'].sum().sort_values(ascending=False).head(10)
ventas_por_categoria.plot(kind='bar', figsize=(10, 6))
plt.title('Ventas totales por categoría (Top 10)')
plt.xlabel('Categoría')
plt.ylabel('Ventas (Dólares)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()